- name: link dotfiles
  file:
    src: "~/.config/devenv/files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
  with_items:
    - .gitconfig
    - .mackup.cfg
    - .profile
    - .skhdrc
    - .sleepscript
    - .tmux.conf
    - .vimrc
    - .yabairc
    - .zshrc

- name: create dir .mackup
  file:
    path: ~/.mackup
    state: directory
    recurse: no

- name: link .mackup/custom.cfg
  file:
    src: ~/.config/devenv/files/mackup_custom.cfg
    dest: ~/.mackup/custom.cfg
    state: link
    force: yes
