- name: link dotfiles
  file:
    src: "~/.config/devenv/files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
  with_items:
    - .chunkwmrc
    - .gitconfig
    - .profile
    - .skhdrc
    - .tmux.conf
    - .vimrc
    - .zshrc
    - .mackup.cfg # todo
    - .sleepscript # todo

# todo
- name: create dir .mackup
  file:
    path: ~/.mackup
    state: directory
    recurse: no

# todo
- name: link .mackup/custom.cfg
  file:
    src: ~/.dotfiles/.mackup/custom.cfg
    dest: ~/.mackup/custom.cfg
    state: link
    force: yes
