- name: install custom iosevka font
  copy:
    src: ~/.config/devenv/files/iosevka-custom/
    dest: ~/Library/Fonts/

- name: install base16 scripts
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.config/base16-shell
    update: yes

# does not run with zsh
# - name: pick a base16 theme
#   shell: base16_circus
#   args:
#     executable: /bin/zsh

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: yes

- name: install all vim plugins
  shell: vim +PluginInstall +qall
  changed_when: False

# taskwarrior setup

- name: clone taskdata repo
  git:
    repo: git@github.com:jerryliu55/taskdata.git
    dest: ~/.task/
    update: no

- name: link .taskrc
  file:
    src: "~/.task/.taskrc"
    dest: "~/.taskrc"
    state: link
    force: yes

# timewarrior automatically stop on sleep

- name: add sleepwatcher daemon plist
  file:
    src: "~/.config/devenv/files/de.bernhard-baehr.sleepwatcher-20compatibility.plist"
    dest: "/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility.plist"
    state: hard
  become: yes
  become_user: root
  become_method: su

- name: check if sleepwatcher is running
  command: launchctl list de.bernhard-baehr.sleepwatcher
  register: launchctl_sleepwatcher
  ignore_errors: true
  changed_when: false

- name: load sleepwatcher launch agent
  command: launchctl load /Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility.plist
  when: launchctl_sleepwatcher.rc == 113
