- name: initialize the iosevka submodule
  shell: git submodule init && git submodule update
  args:
    chdir: ~/.config/devenv

- name: install custom iosevka font
  copy:
    src: ~/.config/devenv/files/iosevka-custom/
    dest: ~/Library/Fonts/

- name: install base16 scripts
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.config/base16-shell
    update: yes

# does not run with zsh
# - name: pick a base16 theme
#   shell: base16_circus
#   args:
#     executable: /bin/zsh

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: yes

- name: install all vim plugins
  shell: vim +PluginInstall +qall
  args:
    executable: "/bin/zsh"
  changed_when: False

- name: install tmux plugin manager (tpm)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: yes

# timewarrior automatically stop on sleep

- name: add sleepwatcher daemon plist
  file:
    src: "~/.config/devenv/files/de.bernhard-baehr.sleepwatcher-20compatibility.plist"
    dest: "/Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility.plist"
    state: hard
  become: yes
  become_user: root
  become_method: su

- name: check if sleepwatcher is running
  command: launchctl list de.bernhard-baehr.sleepwatcher
  register: launchctl_sleepwatcher
  ignore_errors: true
  changed_when: false

- name: load sleepwatcher launch agent
  command: launchctl load /Library/LaunchAgents/de.bernhard-baehr.sleepwatcher-20compatibility.plist
  when: launchctl_sleepwatcher.rc == 113
