- name: install custom iosevka font
  copy:
    src: ~/.config/devenv/files/iosevka-custom/
    dest: ~/Library/Fonts/

- name: install base16 scripts
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/projects/base16-shell
    update: yes
