- name: tap yabai
  homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: install yabai
  homebrew:
    name: yabai
    state: present

- name: install skhd
  homebrew:
    name: koekeishiya/formulae/skhd
    state: present
